# # See https://pre-commit.com for more information
# # See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.11.7
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix]
          # Run the formatter.
          - id: ruff-format

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            # exlude j2
            exclude: ^.*\.j2$
          - id: check-yaml
          - id: check-added-large-files
            args: ["--maxkb=5000"]
          - id: check-ast
          - id: check-docstring-first
          - id: detect-private-key

    - repo: https://github.com/adamchainz/blacken-docs
      rev: 1.19.0 # replace with latest tag on GitHub
      hooks:
          - id: blacken-docs
            additional_dependencies:
                - black==22.12.0

    # shows old code and how to update it
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.19.1
      hooks:
          - id: pyupgrade
            args: [--py310-plus]

    - repo: https://github.com/tcort/markdown-link-check
      rev: v3.12.2
      hooks:
        - id: markdown-link-check
          args: [-q]

    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.6
      hooks:
        - id: shellcheck
          name: shellcheck
          args: ["--severity=warning"]
          stages: [manual]

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.29.4
      hooks:
        - id: check-github-workflows
          args: ["--verbose"]

    - repo: https://github.com/codespell-project/codespell
      rev: "v2.2.6"
      hooks:
      - id: codespell
        args: ["-L", "nin"]
        stages: [manual]

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: '1.15.0'  # Use the sha / tag you want to point at
        hooks:
        -   id: mypy