services:
  qdrant:
    image: qdrant/qdrant:v1.14.0
    container_name: qdrant 
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    ports:
      - 6333:6333 # tcp
      - 6334:6334 # grpc
    volumes:
      - ./db:/qdrant/storage
    restart: always